---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  labels:
    app: haproxy-ingress
  disableNameSuffixHash: true

namespace: haproxytech
configMapGenerator:
- name: haproxy-ingress-values
  behavior: create
  files:
  - values.yaml

###
