---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-vip
  labels:
    app: excalidraw
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    name: http
    targetPort: 80
  selector:
    app.kubernetes.io/name: excalidraw
###
