### Convert to helmchartconfig
### 
      rke2-cilium:
        autoDirectNodeRoutes: true
        bandwidthManager:
          bbr: true
          enabled: true
        bpf:
          hostLegacyRouting: false
          masquerade: true
        enableIPv4Masquerade: true
        endpointRoutes:
          enabled: true
        installNoConntrackIptablesRules: true
        ipam:
          mode: kubernetes
        ipv4:
          enabled: true
        ipv4NativeRoutingCIDR: 10.42.0.0/16
        k8sServiceHost: 127.0.0.1
        k8sServicePort: 6443
        kubeProxyReplacement: true
        operator:
          enabled: true
          replicas: 1
        routingMode: native
