---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  labels:
    app: zot
  disableNameSuffixHash: true

namespace: zot-system
configMapGenerator:
- name: zot-values
  behavior: create
  files:
  - values.yaml

###
